### ISSUE TITLE
Error in line 233

### ISSUE THREAD

**Issue by ghost** [mcourteaux/QuineMcCluskey#1]
Hello,
I am just trying to realize a minimized 4 bit 8 output function for one my school projects. I, first, attempted to create my QuineMcCluskey program, with currently about 300 lines of code. However, I recently just hit rock bottom when my code started failing out of nowhere and its just went spiraling down from there. I would love to fix my code, but with the time constraints I have, I began looking for an alternative. All of the open-source code that I have found in GitHub would not compile in my Dev C++ IDE. In line 233, its states that the variable "it" is not properly initialized so I added "int" before. However, then function within the same line "allNumbers.begin()" is not collaborating since the compiler is stating that "no match for 'operator!=' and that it cannot convert 'std::set<int>::iterator  to int. This occurs multiples times throughout the code, so I am assuming that it must be something wrong with my compiler. Should I make sure to have a specific compiler or how would I resolve the issue? Thank you for your time.

**Comment by mcourteaux** [comment]
Well, the `auto` keyword is a C++11 feature. You will have to set your compiler to C++11. For GCC and Clang this is done by `-std=c++11`. In case you do not want to use auto, just replace it with `std::set<int>::iterator`. (So it is definitely not an int).
